MODEL:
  META_ARCHITECTURE: "RetinaNet"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
    NMS_THRESH: 0.5
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2500
RETINANET:
  RETINANET_ON: True
  NUM_CLASSES: 81
  PRIOR_PROB: 0.02
  SCALES_PER_OCTAVE: 3
  STRADDLE_THRESH: -1
FREEANCHOR:
  FREEANCHOR_ON: True
  PRE_ANCHOR_TOPK: 50
  BBOX_THRESHOLD: 0.6
  BBOX_REG_WEIGHT: 0.75
  FOCAL_LOSS_ALPHA: 0.5
  FOCAL_LOSS_GAMMA: 2.0
OUTPUT_DIR: outputs/free_anchor_R-50-FPN_1x
